
# mongo
mongodb.host: mongo-${spring.profiles.active}.vpclub.io
mongodb.port: 27017
#mongodb.username=
#mongodb.password=
mongodb.dbname: axon
mongodb.events.collection.name: events
mongodb.events.snapshot.collection.name: snapshots
